### ISSUE TITLE
Doesn't work on Apple Silicon Unity 2021

### ISSUE THREAD

**Issue by SSS135** [netpyoung/unity.webp#39]
Hi,

I'm using MacBook with M1 CPU. I updated Unity to 2021.2 for Apple Silicon CPU. Now I get DLLNotFoundException because plugin doesn't have arm64 dlls. Can you please help?

**Comment by netpyoung** [comment]
prebuilt script maintained on https://github.com/netpyoung/prebuilt-libwebp which had library build script.
And I modified my build script to create a universal macOs library which supports x86_64 and arm64 both.

https://github.com/netpyoung/prebuilt-libwebp/releases/download/v0.0.5/macos.zip

Could you try to download above zip then replace unity.webp/Plugins/x64 's bundles then test?

Let me know if that works or not. If it works, I will reflect that on unity.webp also.

**Comment by SSS135** [comment]
Thank you for quick answer. I've replaced the bundles with the ones you provided but it caused macOS error: “webp.bundle” cannot be opened because the developer cannot be verified.
<img width="283" src="https://user-images.githubusercontent.com/2598518/160998187-5b26b9bd-adb9-4cfe-a01d-95c0b773b360.png">

**Comment by netpyoung** [comment]
@SSS135 

That caused by macOs's feature which when you download something from web, macOS will insert signature that is unsigned.
But it seems from download via package manager.

I didn't fully tested with arm64 silicon macOS with that zip. but I willl push that(hope will be worked well).
Anyway, Could you try this release (https://github.com/netpyoung/unity.webp/releases/tag/0.3.3) ?
Then please feedback to me which is work well or not.

**Comment by SSS135** [comment]
@netpyoung It works, thank you! Though there was a slight issue of *.bundle files being set to Intel instead of any CPU.

**Comment by netpyoung** [comment]
Thanks your feedback.
I fixed that (https://github.com/netpyoung/unity.webp/commit/43ff404fb5e9b403b06f8f2f422138cac68091cf)
then applied on 0.3.4
